### PR TITLE
added high level test cases for settings

### PR DESCRIPTION
**Pull request by wienio03**
Filipie bardzo proszę ubłagalnie o zaakceptowanie tego pull requesta.

### CODE REVIEW

**Comment by filiera** [comment]
Please add a header saying what part of COSMIC is being tested, please add an explanation of what the test case is about

**Review by filiera — CHANGES_REQUESTED** [review]
^^

**Review by KajetanOzog — CHANGES_REQUESTED** [review]
Kindly request to change the header.

**Review by filiera — APPROVED** [review]
# #

**Review by KajetanOzog — APPROVED** [review]
Beautiful!!!

**Pull request merged**
